
const calcOrderTotal = (o) =>
    o.invoice.items.reduce((sum, item) => sum + item.unitPrice * item.qty + (item.addOnPrice || 0), 0);

const fmt = (n) => "₱" + Number(n).toLocaleString("en-PH", { minimumFractionDigits: 0 });

const todayLabel = () =>
    new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });

export function exportToPDF({ orders, appointments, expenseBreakdown, totalExpenses }) {
    const totalAllOrders = orders.reduce((sum, o) => sum + calcOrderTotal(o), 0);
    const totalPaidOrders = orders
        .filter(o => o.invoice.status === "Paid")
        .reduce((sum, o) => sum + calcOrderTotal(o), 0);

    const badge = (label) => label ?? "—";

    const orderRows = orders.map(o => `
        <tr>
            <td>${o.id}</td>
            <td>${o.item}</td>
            <td>${o.customer}</td>
            <td>${o.date}</td>
            <td>${o.estimatedCompletion ?? "—"}</td>
            <td>${badge(o.serviceType)}</td>
            <td style="font-weight:700">${fmt(calcOrderTotal(o))}</td>
            <td>${badge(o.invoice.status)}</td>
            <td>${badge(o.status)}</td>
        </tr>
    `).join("");

    const apptRows = appointments.map(a => `
        <tr>
            <td>${a.id}</td>
            <td>${a.service}</td>
            <td>${a.customer}</td>
            <td>${a.tailor}</td>
            <td>${a.date}</td>
            <td>${a.time}</td>
            <td>${badge(a.status)}</td>
        </tr>
    `).join("");

    const expenseRows = expenseBreakdown.map(e => `
        <tr>
            <td>
                <span style="display:inline-block;width:10px;height:10px;border-radius:50%;
                    background:${e.color};margin-right:6px;vertical-align:middle">
                </span>
                ${e.name}
            </td>
            <td style="font-weight:700">${e.value}%</td>
            <td>${fmt(Math.round(totalExpenses * e.value / 100))}</td>
        </tr>
    `).join("");
    const html = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>JJS-Track Report — ${todayLabel()}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body        { font-family: 'Segoe UI', sans-serif; color: #111; background: #fff; padding: 32px; font-size: 12px; }
        h1          { font-size: 20px; font-weight: 800; color: #0f172a; }
        h2          { font-size: 14px; font-weight: 700; color: #1e293b; margin-bottom: 10px; }
        .subtitle   { font-size: 12px; color: #94a3b8; margin-top: 2px; }
        .header     { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 28px; border-bottom: 2px solid #e2e8f0; padding-bottom: 16px; }
        .stats      { display: flex; gap: 16px; margin-bottom: 28px; }
        .stat       { flex: 1; background: #f8fafc; border-radius: 10px; padding: 14px 18px; border-top: 3px solid #e2e8f0; }
        .stat-val   { font-size: 22px; font-weight: 800; }
        .stat-lbl   { font-size: 11px; color: #6b7280; margin-top: 2px; }
        section     { margin-bottom: 28px; }
        table       { width: 100%; border-collapse: collapse; font-size: 11px; }
        thead tr    { background: #f1f5f9; }
        th          { padding: 8px 10px; text-align: left; font-size: 10px; font-weight: 700; color: #6b7280; text-transform: uppercase; letter-spacing: .5px; }
        td          { padding: 9px 10px; border-bottom: 1px solid #f1f5f9; color: #374151; }
        tfoot td    { border-top: 2px solid #e2e8f0; background: #f8fafc; font-weight: 800; color: #1d4ed8; font-size: 13px; padding: 10px; }
        .footer     { margin-top: 32px; text-align: center; font-size: 10px; color: #cbd5e1; border-top: 1px solid #f1f5f9; padding-top: 16px; }
        @media print { body { padding: 16px; } }
    </style>
</head>
<body>

    <!-- Header -->
    <div class="header">
        <div>
            <h1>JJS-Track · Dashboard Report</h1>
            <p class="subtitle">${todayLabel()}</p>
        </div>
        <div style="text-align:right;font-size:11px;color:#6b7280">Generated by JJS-Track</div>
    </div>

    <!-- Summary Stats -->
    <div class="stats">
        <div class="stat">
            <div class="stat-val">${orders.length}</div>
            <div class="stat-lbl">Total Order No.</div>
        </div>
        <div class="stat">
            <div class="stat-val">${fmt(totalPaidOrders)}</div>
            <div class="stat-lbl">Total Revenue (Paid)</div>
        </div>
        <div class="stat">
            <div class="stat-val">${fmt(totalExpenses)}</div>
            <div class="stat-lbl">Total Expenses</div>
        </div>
        <div class="stat">
            <div class="stat-val">${fmt(totalAllOrders)}</div>
            <div class="stat-lbl">Total Orders</div>
        </div>
    </div>

    <!-- Orders -->
    <section>
        <h2>Orders (${orders.length} total)</h2>
        <table>
            <thead>
                <tr>
                    <th>Order ID</th><th>Item</th><th>Customer</th><th>Date</th>
                    <th>Est. Completion</th><th>Service</th><th>Total</th>
                    <th>Invoice</th><th>Status</th>
                </tr>
            </thead>
            <tbody>${orderRows}</tbody>
            <tfoot>
                <tr>
                    <td colspan="6">Grand Total (All Orders)</td>
                    <td>${fmt(totalAllOrders)}</td>
                    <td colspan="2"></td>
                </tr>
            </tfoot>
        </table>
    </section>

    <!-- Appointments -->
    <section>
        <h2>Appointments (${appointments.length} total)</h2>
        <table>
            <thead>
                <tr>
                    <th>#</th><th>Service</th><th>Customer</th><th>Tailor</th>
                    <th>Date</th><th>Time</th><th>Status</th>
                </tr>
            </thead>
            <tbody>${apptRows}</tbody>
        </table>
    </section>

    <!-- Expense Breakdown -->
    <section>
        <h2>Expense Breakdown — ${fmt(totalExpenses)} total</h2>
        <table>
            <thead>
                <tr><th>Category</th><th>Share</th><th>Amount</th></tr>
            </thead>
            <tbody>${expenseRows}</tbody>
            <tfoot>
                <tr>
                    <td>Total</td>
                    <td>100%</td>
                    <td>${fmt(totalExpenses)}</td>
                </tr>
            </tfoot>
        </table>
    </section>

    <div class="footer">JJS-Track · ${todayLabel()}</div>

    <script>window.onload = () => { window.print(); }</script>
</body>
</html>`;

    const win = window.open("", "_blank");
    win.document.write(html);
    win.document.close();
}